import time
from selenium.webdriver.common.by import By
from .base_page import BasePage

class Add_new_boat(BasePage):
    collapse = (By.XPATH, "//span[@class='ant-btn-icon']")
    boat_menu = (By.XPATH , "//ul[@role='menu']//div[@title='My Boats']")
    add_new_boat_button = (By.XPATH , "//span[normalize-space()='Add New Boat']")
    # Boat Information
    boat_name = (By.XPATH , "//input[@id='boatName']")
    model = (By.XPATH , "//input[@id='model']")
    shipyard = (By.XPATH , "//input[@id='shipyard']")
    construction_year = (By.XPATH , "//input[@id='year']")
    length = (By.XPATH , "//input[@id='length']")
    width = (By.XPATH , "//input[@id='width']")
    draft = (By.XPATH , "//input[@id='draft']")
    air_draft = (By.XPATH , "//input[@id='airDraft']")
    weight = (By.XPATH , "//input[@id='weight']")
    propulsion = (By.XPATH , "//input[@id='propulsion']")
    hull_type = (By.XPATH , "//input[@id='hullMaterial']")
    country = (By.XPATH , "//input[@id='country']")
    home_port = (By.XPATH , "//input[@id='homePort']")
    registration_number = (By.XPATH , "//input[@id='registrationNumber']")
    photos = (By.XPATH , "//span[@class='ant-upload']")
    input_photos = (By.XPATH,"//input[@name='file']")
    upload_documents_button =(By.XPATH , "//button[@title='Upload Documents']")
    Document_type = (By.XPATH , "//div[@class='ant-modal-content']")
    Add_boat_button = ()

    def add_new_boat(self):
        self.click(*self.collapse)
        self.click(*self.boat_menu)
        time.sleep(2)
        assert self.get_current_url() ==   "https://dev-marinapy.pysquad.com/boats" , "My boats page not working"
        self.click(*self.collapse)
        self.click(*self.add_new_boat_button)
        time.sleep(2)
        assert self.get_current_url()  == "https://dev-marinapy.pysquad.com/boats/add-new-boat" , "Add new boats page not working"
        self.click(*self.boat_name)
        self.send_keys1((self.boat_name)  , "MOON BOAT")
        self.tab_keys(*self.boat_name)
        self.send_keys1((self.model), "MOON MODEL")
        self.tab_keys(*self.model)
        self.send_keys1((self.shipyard), "SHIPYARD")
        self.tab_keys(*self.shipyard)
        self.send_keys1((self.construction_year), "2020")
        self.tab_keys(*self.construction_year)
        self.send_keys1((self.length),"2")
        self.tab_keys(*self.length)
        self.send_keys1((self.width), "3")
        self.tab_keys(*self.width)
        self.send_keys1((self.draft) , "2")
        self.tab_keys(*self.draft)
        self.send_keys1((self.air_draft),"5")
        self.tab_keys(*self.air_draft)
        self.send_keys1((self.weight),"100")
        self.tab_keys(*self.weight)
        self.enter_key(*self.propulsion)
        self.down_key(*self.propulsion)
        self.enter_key(*self.propulsion)
        self.tab_keys(*self.propulsion)
        self.enter_key(*self.hull_type)
        self.down_key(*self.hull_type)
        self.enter_key(*self.hull_type)
        self.tab_keys(*self.hull_type)
        self.send_keys1((self.country), "India")
        self.down_key(*self.country)
        self.enter_key(*self.country)
        self.tab_keys(*self.country)
        self.send_keys1((self.home_port), "HOME PORT 1")
        self.tab_keys(*self.home_port)
        self.click(*self.registration_number)
        self.send_keys1((self.registration_number), "384002")
        self.tab_keys(*self.registration_number)
        self.click(*self.photos)
        self.upload_file((self.input_photos),"/home/pys/Pictures/Screenshots/Screenshot from 2026-01-05 12-17-36.png")
        self.click(*self.upload_documents_button)
        time.sleep(2)

        # self.swi(*self.Document_type)
        # print("Successfully switch frame")
        # self.click(*self.Document_type)
        # print("clicked on document type ")



